from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
README_PATH = REPOSITORY_ROOT / "README.md"
STRUCTURE_ENTRIES = [
    ("music-catalog/", "project and catalog metadata"),
    ("releases/", "release metadata and schemas"),
    ("sync_cues/", "sync cue metadata and examples"),
    ("automation/scripts/", "README automation utilities"),
    ("scripts/", "repository catalog utilities"),
    ("src/", "Python source files"),
    ("Studio Workflow Notes/", "studio process documentation"),
    ("turbo-adventure/metadata/", "track metadata examples"),
]


def build_readme() -> str:
    structure_lines = "\n".join(
        f"- `{path}` — {description}" for path, description in STRUCTURE_ENTRIES
    )
    return (
        "# Dutcheyy Studio Music Catalog\n\n"
        "A structured repository for managing Dutcheyy Studio music catalog "
        "assets, metadata, sync materials, releases, and workflow notes.\n\n"
        "## Repository Structure\n"
        f"{structure_lines}\n\n"
        "## Automation\n"
        "This README is generated by `automation/scripts/generate-readme.py`.\n"
    )


def main() -> int:
    readme_content = build_readme()
    current = README_PATH.read_text(encoding="utf-8") if README_PATH.exists() else None
    if current == readme_content:
        print("README.md is already up to date.")
        return 0

    README_PATH.write_text(readme_content, encoding="utf-8", newline="\n")
    print(f"Updated {README_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
