from pathlib import Path
from textwrap import dedent


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
README_PATH = REPOSITORY_ROOT / "README.md"
README_CONTENT = dedent(
    """\
    # Dutcheyy Studio Music Catalog

    A structured repository for managing Dutcheyy Studio music catalog assets, metadata, sync materials, releases, and workflow notes.

    ## Repository Structure
    - `music-catalog/` — project and catalog metadata
    - `releases/` — release metadata and schemas
    - `sync_cues/` — sync cue metadata and examples
    - `scripts/` — repository automation utilities
    - `src/` — Python source files
    - `Studio Workflow Notes/` — studio process documentation
    - `turbo-adventure/metadata/` — track metadata examples

    ## Automation
    This README is generated by `automation/scripts/generate-readme.py`.
    """
)


def main() -> int:
    current = README_PATH.read_text(encoding="utf-8") if README_PATH.exists() else None
    if current == README_CONTENT:
        print("README.md is already up to date.")
        return 0

    README_PATH.write_text(README_CONTENT, encoding="utf-8", newline="\n")
    print(f"Updated {README_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
