name: Repository He**th Check

on**  push:
    branches:
      - mai**
jobs**  health-check:
    runs-on: ubun**-latest

    steps**      - name: Checkout Repository**       uses: actions/checkout@**

      - name: List Files
      **run: ls -R

      -**ame**Check JSON Files
        run: |
 **       find . -name "*.json" -exe***ython -m json.tool {} \;
